export const IMG_DATA_RECEIVED_ACTION = "IMG_DATA_RECEIVED";
export const FILTER_DATA_ACTION = "FILTER_DATA";
export const PAGINATION_LINK_CLICK_ACTION = "PAGINATION_LINK_CLICK";
export const ERROR_ACTION = "ERROR";
